### ISSUE TITLE
 can you proxy all  request in android 8?

### ISSUE THREAD

**Issue by hhhaiai** [heiher/hev-dns-proxy#1]
can you proxy all  request in android 8?

**Comment by heiher** [comment]
I'm not sure, Not tested on Android 8.
You can try it if you have Android 8 devices. :)

**Comment by hhhaiai** [comment]
ok.

**Comment by hhhaiai** [comment]
> I'm not sure, Not tested on Android 8.
> You can try it if you have Android 8 devices. :)

can you gave me thie use method.

**Comment by hhhaiai** [comment]
> > I'm not sure, Not tested on Android 8.
> > You can try it if you have Android 8 devices. :)
> 
> can you gave me thie use method.

android 8 and 9 has no root.  what can I do.

**Comment by heiher** [comment]
Root first. :smiley:

**Comment by heiher** [comment]
Looks the netd source code of Android 8.0.0, I think this implementation is still compatible with it.
