### ISSUE TITLE
[request] user friendly version

### ISSUE THREAD

**Issue by gilcu3** [heiher/hev-dns-proxy#2]
Is it possible to come up with a simple magisk module for this, I would use it with afwall+ and it would be great for controlling data usage completely. Right now I have to disable netd in afwall+ and then set up individual ip addresses for every domain I need in hosts file. Using this project afwall+ would detect correct uid in dns requests and block them per app basis...

**Comment by heiher** [comment]
Sorry. I don't know how to make a magisk module.

**Comment by gilcu3** [comment]
could you explain which files need to be modified in the file system, for example what does this line in How to Run do:
`
mv dnsproxyd hev-dns-proxy; mv dnsproxyd.netd dnsproxyd
`
Understanding a little bit how it works I could make a magisk module for myself and other...

**Comment by heiher** [comment]
> could you explain which files need to be modified in the file system, for example what does this line in How to Run do:
> `mv dnsproxyd hev-dns-proxy; mv dnsproxyd.netd dnsproxyd`
> Understanding a little bit how it works I could make a magisk module for myself and other...

Oh! This is a mistake. I have already updated the README.

## How to Run

```bash
# Switch to root user
adb root
# Push executable to device
adb push hev-dns-proxy /data/hev-dns-proxy
adb shell
# Run new dns proxy in background
/data/hev-dns-proxy -p /dev/socket/hev-dns-proxy -a 8.8.8.8 -b 8.8.4.4 &
cd /dev/socket
# Change ownership and SELinux context for socket file of new dns proxy
chown root:inet hev-dns-proxy
chcon u:object_r:dnsproxyd_socket:s0 hev-dns-proxy
# Backup socket file of netd
mv dnsproxyd dnsproxyd.netd
# Enable new dns proxy
mv hev-dns-proxy dnsproxyd
```
I think you should write a service manage script to run that dns proxy after netd booted, and switch the socket file.
